Fix cli with None, REPL with non-ascii input, ctrl-D
ScientificThought/mathinterpreter pull request #66
Opened 2024-05-27 20:52 UTC by aureliobarbosa

Now the REPL behaves as expected... 

```bash
❯ mathinterpreter
calc > 🐍
Invalid input. Non-ASCII character(s) were giving as input.
calc > c
Illegal character 'c'
calc >              # <--- Ctrl-C
 Program interrupted by user.
```

```bash
❯ mathinterpreter
calc >              # <--- Ctrl-D
EOFError
```

2024-05-27 23:43 UTC, hsguidi requested changes
Just a readability suggestion. It is up to you accept it or not.

2024-05-27 23:43 UTC, hsguidi commented on mathinterpreter/__main__.py
>      while repl:
I suggest to insert the test "len(sys.argv)==1" inside the cli function, and do something like this:

if len(sys.argv)>1:
    cli(sys.argv)
else:
    while True:
        ....

I believe that this way will improve readability.
Note that I do not like loops like "while True:", but it seems to be a common practice in python language, and it is compatible with the EAFP principle.

2024-05-28 20:50 UTC, aureliobarbosa commented
Hey @hsguidi. 

Just did your fixes. I simplified the code for capturing exceptions.

2024-05-28 20:52 UTC, aureliobarbosa commented
With current implementation there is a consistency between CLI and REPL error messages.

```bash
❯ mathinterpreter
calc > 🐍
Illegal character '🐍'
```
```bash
❯ mathinterpreter 🐍
Illegal character '🐍'
```

2024-05-29 01:15 UTC, hsguidi approved these changes
Thank you.

2024-05-29 01:16 UTC, merged